######### System #########
device: cuda
device_id: 3
log_wandb: True
wandb_project: DFFKE
wandb_name: Ablation - Gaussian_DP_0.40

algorithm: DFFKE

######### DFFKE Setting #########
decoder_model: LatentGenerator # LatentGenerator / ClassLatentGenerator
knowledge_exchange_rounds: 50
local_align_acc: 0.98
decoder_train_epoch: 6
FKE_epoch: 4
clustering_iteration: 100 # 100 is usually enough to have clustering network to converge

# Ablation Controls
additive_gaussian_DP: 0.40

save_clients: True
checkpoint_dir: ./checkpoints/
######### Load Clients checkpoints #########
#load_clients: null
load_clients: ./checkpoints/warmup/
#load_clients: ./checkpoints/knowledge_exchange/