######### System #########
device: cuda
cuda_gpu: 0
log_wandb: True
wandb_project: BlackBoxFL
wandb_name: testing

######### FL Setting #########
n_clients: 10
client_encoder: ResNet18_32x32 # ResNet18_32x32
#client_encoder: clip_vit_tiny
#client_encoder: vit_base_patch16_clip_224.openai
seed: 0
dataset: CIFAR100 # CIFAR10 / CIFAR100 / FC100
redo_ds_split: False
data_dir: ./data/
data_partition: non_iid_balanced # iid, non_iid_unbalanced, non_iid_balanced
alpha: 1.0 # Degree of non-iid data split (0.1 High Hetero, 1.0 Medium Hetero, 10.0 Low Hetero); if null, perfect iid

FL_algorithm: DFFKE # DFFKE / FedAvg / DFRD / FedFTG / DENSE

######### DFFKE Setting #########
warmup_clients: False
local_acc: 0.95
save_clients: False
knowledge_exchange_rounds: 20
generator_model: LatentGenerator #CGeneratorA / LatentGenerator / ClassLatentGenerator
local_align_after_knowledge_exchange: True
new_client_opt_every_round: True
dock_kd: True # Dock or Emb
cls_clustering: True
L2G_epoch: 1
L2G_augment_logits: False
L2G_use_emb_md_loss: False  #\ Only One
L2G_use_logit_md_loss: True #/ Only One
G2L_epoch: 1
G2L_local_review_iteration: 1
G2L_data_bank_iteration: 1
G2L_augment_real: False
G2L_cal_emb_loss: True


checkpoint_dir: ./checkpoints/
######### Load Clients checkpoints #########
#load_clients: null
load_clients: ./checkpoints/warmup/
#load_clients: ./checkpoints/knowledge_exchange/


# Training Hyper-parameters
client_lr: 0.001
generator_model_lr: 0.001
reg: 1.0e-05
batch_size: 100


######### Other #########
# Only for few-shot learning
meta_config:
  num_train_tasks: 500
  num_test_tasks: 10
  train_client_class: 5
  train_support_num: 5
  train_query_num: 15
  test_client_class: 5
  test_support_num: 5
  test_query_num: 15
  test_k: [5]
  test_ft_lr: 0.001
  test_ft_approach: contrastive # prototype / contrastive / classic
  test_ft_steps: 20
  test_use_docking: False # Embedding / Docking
  aug_types: [color, translation]
  aug_prob: 1.0